### ISSUE TITLE
MouseEvent offset greater than position

### ISSUE THREAD

**Issue by hellow554** [gyscos/Cursive#172] opened 2017-12-15 11:01 UTC
I clicked around in my view to see, if I can get any errors, and so I got one, but not an expected one.
I thought, that when you receive a mouse event the position.x must be greater/equals to the offset.x (same for y, but it's not.
I got something like this:

    p event
    $2 = cursive::event::Event::Mouse{offset: cursive::xy::XY<usize> {x: 49, y: 32}, position: cursive::xy::XY<usize> {x: 48, y: 41}, event: cursive::event::MouseEvent::Press(cursive::event::MouseButton::Left)}

Is this a false assumption of mine or a bug?
I have a full coredump, but sadly I am not able to share it because of IP reasons. If you need anything to know, I should be able to answer this. Maybe I can create a MCVE but don't rely on that :)

**Comment by gyscos** [comment] 2017-12-16 07:50
Hi!

It's not a bug, events can indeed be from outside the view itself. That's the main reason to have this separate position and offset values, rather than just having a relative position. You can see some of the concerns that were considered here: https://github.com/gyscos/Cursive/wiki/Design:-mouse-support.

A few methods can help dealing with this: [`Vec2::checked_sub`](https://docs.rs/cursive/0.7.5/cursive/struct.XY.html#method.checked_sub), [`Vec2::fits_in`](https://docs.rs/cursive/0.7.5/cursive/struct.XY.html#method.fits_in), and a few others in there.

Still, I agree it may not be completely painless; the whole mouse support is still very recent, and may take a few changes to feel right.

**Comment by gyscos** [comment] 2018-07-26 05:03
I'll close this as the main reason is part of the design. Feel free to re-open to discuss the design decision itself.

**Closed by gyscos** 2018-07-26 05:03 UTC
Labels: question
