### ISSUE TITLE
TextView sometimes doesn't re-fill text for increased view width

### ISSUE THREAD

**Issue by neilvandyke** [gyscos/Cursive#236] opened 2018-05-04 05:08 UTC
# Problem description

Under certain conditions that occur very frequently for me, the text in a TextView will not re-fill (reflow) when the terminal program width has increased more than enough that text should re-fill.

Although I can't yet exactly characterize the conditions that cause this, I can reproduce it quite quickly.  It usually happens when there is no scrollbar, but can happen (much more rarely) when there is a scrollbar.

To reproduce this:

1. Make a file "assets/lorem-short.txt" that consists of only the first 1-2 paragraphs of "assets/lorem.txt".
2. Temporarily edit "examples/lorem.rs" to use file "../assets/lorem-short.txt".
3. Resize your terminal window to (very roughly) a typical 80x24 size.
4. cargo run --example lorem
5. Dismiss the initial Dialog.
6. Make sure that the TextView has no scrollbar, and that there are at least 2 (1?) blank lines in the TextView below the text.
7. Keep incrementally increasing the width of the terminal window (without decreasing the height enough to cause a TexView scrollbar to appear).  BUG: You might initially see a re-fill of the text, to use up to several more columns of width, but then the text will stop re-filling for further increases of window width.  All line-drawing and other parts of the terminal display look correct.

I reproduce this bug easily in rxvt-unicode.  I haven't tried other terminals.

For additional characterization, you can do things like:

* Try decreasing the terminal width, and then increasing it, to find that the re-fill likely stops at a different width than initially.
* When the text won't re-fill for a width increase, try decreasing the terminal *height* until a TextView scrollbar appears, at which time the text should be filled normally -- immediately, and for subsequent horizontal resizes as long as the scrollbar is visible.  (Or, perhaps, so long as there are no blank visible below the text, since the bug *might* not occur when the text fills all height of the TextView without triggering the scrollbar.)

A naive guess is that the cause involves a test for whether the rows cache is valid, or that some part of the TextView doesn't get the right width information from a screen layout sometimes, but you can debug this a thousand times faster than I can. :)

(Note that there might also be another symptom of this bug or a different bug, when scrollbars are present.  When I was "fuzz-testing" by constantly resizing width back and forth with scrollbars present, but also occasionally resizing height sometimes (including enough to cause scrollbar to disappear at least once), I did get it into a state in which scrollbar was present but text was not re-filling, no matter how much I increased the width.  (I suppose this possibly different bug might have been triggered by either temporarily making the window too high, such that the scrollbar termporarily disappeared, or it might have been because I temporarily made the terminal window too short for the TextView.)  What I described in this paragraph might be a red herring or a different bug, and I don't mean to confuse the bug report above.)

Thank you.

# Environment

* Operating system: Debian GNU/Linux 9.4 stable
* Backend used: ncurses 6.0+20161126-1+deb9u2
* Current locale: en_US.UTF-8
* Cursive version: git commit d4ced015f62ed3a3bce502cdffa06f486d57b5e1

**Comment by gyscos** [comment] 2018-05-05 16:06
Hi, and thank you very much for the report!

Indeed, it was a cache problem, but more convoluted than I thought: it was actually caused by the rows making algorithm.

Anyway, this should be fixed now in 20cb033b8d3c1edab642d9c068443cdd4d7c38b1.

**Comment by gyscos** [comment] 2018-07-26 04:51
Fix was released in 0.9.0.

**Closed by gyscos** 2018-07-26 04:51 UTC
